version: '3.9'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET_KEY=${BYBIT_API_SECRET_KEY}
